title: Sprintime
baseurl: /
permalink: '/:title/'
palette: orange
header:
  title: Sprintime
  logo_img: ''
  has_nav: true
  menu:
    actions:
      - label: Sign Up
        url: /signup
footer:
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  has_subscribe: true
  social_title: Community
  tagline: SaaS theme by Stackbit
  logo_img: ''
  has_social: true
  content: '&copy; Stackbit. All rights reserved.'
  links:
    - text: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
  nav_title: Sprintime
  has_nav: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: '/posts/:title/'
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
